---
abstract: 'a calendar for a month of articles (on the web)'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-AdventCalendar
requires:
  Calendar::Simple: 0
  DateTime: 0
  DateTime::Format::W3CDTF: 0
  Email::Simple: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 2
  HTML::Mason::Interp: 0
  Moose: 0.70
  Path::Class: 0
  Pod::Elemental: 0
  Pod::Elemental::Transformer::List: 0
  Pod::Elemental::Transformer::PPIHTML: 0
  Pod::Elemental::Transformer::Pod5: 0
  Pod::Elemental::Transformer::VimHTML: 0
  Pod::Simple::XHTML: 3.12
  XML::Atom::SimpleFeed: 0
  autodie: 0
resources:
  repository: http://github.com/rjbs/www-adventcalendar
version: 0.100010
